# ============================================================
# CONFIGURACIÓN LOCAL - INSTRUCCIONES
# ============================================================
# 1. Copia este archivo como "application.properties"
#    (ubícalo en src/main/resources/)
# 2. Configura las variables directamente en tu sistema/IDE
#    en IntelliJ: Run > Edit Configurations > Environment Variables
#    Agrega: DB_USER,DB_PASSWORD
# 3. Asegúrate que los valores coincidan con tu .env de Docker Compose
# 4. Levanta la base de datos: docker compose up -d
# 5. Ejecuta la app
# ============================================================

spring.application.name=backend
server.port=${SERVER_PORT:8080}

# Seguridad: Configuración de Orígenes Permitidos (CORS)
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Microservicio FastAPI
# Puerto solo para generar el mock, pronto debe cambiarse al puerto donde corre FastApi
fastapi.url=${FASTAPI_URL:http://localhost:8080}

# Configuración de PostgreSQL
# (username y password son obligatorios como variables de entorno, configurar en IntelliJ/VSC o en el sistema)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hackaton_db}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect