# Perfil de producción (requiere la URL explícita del microservicio de FastAPI)
fastapi.url=${FASTAPI_URL}

# Configuración JPA / Hibernate para producción
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
